<?php
// ============================================
// Nigerian Banks List with Codes
// Source: CBN / NIBSS bank codes
// Includes: Commercial, Microfinance, Fintech, Merchant, Mortgage banks
// ============================================

$nigerian_banks = [
    // Commercial Banks (Tier 1 & 2)
    ['code' => '044', 'name' => 'Access Bank PLC'],
    ['code' => '063', 'name' => 'Access Bank PLC (Diamond)'],
    ['code' => '035', 'name' => 'Wema Bank PLC'],
    ['code' => '033', 'name' => 'United Bank for Africa (UBA) PLC'],
    ['code' => '032', 'name' => 'Union Bank of Nigeria PLC'],
    ['code' => '039', 'name' => 'Stanbic IBTC Bank PLC'],
    ['code' => '068', 'name' => 'Standard Chartered Bank Nigeria'],
    ['code' => '076', 'name' => 'Polaris Bank PLC'],
    ['code' => '082', 'name' => 'Keystone Bank PLC'],
    ['code' => '057', 'name' => 'Zenith Bank PLC'],
    ['code' => '058', 'name' => 'Guaranty Trust Bank (GTBank) PLC'],
    ['code' => '011', 'name' => 'First Bank of Nigeria PLC'],
    ['code' => '214', 'name' => 'First City Monument Bank (FCMB) PLC'],
    ['code' => '070', 'name' => 'Fidelity Bank PLC'],
    ['code' => '050', 'name' => 'Ecobank Nigeria PLC'],
    ['code' => '301', 'name' => 'Jaiz Bank PLC'],
    ['code' => '221', 'name' => 'Stanbic IBTC Bank PLC'],
    ['code' => '215', 'name' => 'Unity Bank PLC'],
    ['code' => '084', 'name' => 'Enterprise Bank PLC (Defunct)'],
    ['code' => '014', 'name' => 'Afribank PLC (Defunct)'],
    ['code' => '023', 'name' => 'CitiBank Nigeria'],
    ['code' => '101', 'name' => 'ProvidusBank PLC'],
    ['code' => '102', 'name' => 'Titan Trust Bank PLC'],
    ['code' => '103', 'name' => 'Globus Bank PLC'],

    // Merchant Banks
    ['code' => '559', 'name' => 'Coronation Merchant Bank'],
    ['code' => '551', 'name' => 'FSDH Merchant Bank'],
    ['code' => '561', 'name' => 'Nova Merchant Bank'],
    ['code' => '526', 'name' => 'Rand Merchant Bank'],

    // Microfinance Banks (Selected Major Ones)
    ['code' => '090175', 'name' => 'Rubies MFB'],
    ['code' => '090176', 'name' => 'Seed Capital MFB'],
    ['code' => '090177', 'name' => 'Ilaro Poly MFB'],
    ['code' => '090178', 'name' => 'Egwafin MFB'],
    ['code' => '090179', 'name' => 'Lapo MFB'],
    ['code' => '090180', 'name' => 'Jessefield MFB'],
    ['code' => '090181', 'name' => 'MICROVIS MFB'],
    ['code' => '090182', 'name' => 'Ndiorah MFB'],
    ['code' => '090183', 'name' => 'WESLEY MFB'],
    ['code' => '090186', 'name' => 'Girei MFB'],
    ['code' => '090188', 'name' => 'Baines Credit MFB'],
    ['code' => '090189', 'name' => 'Esan MFB'],
    ['code' => '090190', 'name' => 'Mutual Benefits MFB'],
    ['code' => '090191', 'name' => 'KCMB MFB'],
    ['code' => '090192', 'name' => 'Midland MFB'],
    ['code' => '090193', 'name' => 'Unical MFB'],
    ['code' => '090194', 'name' => 'NPF MFB'],
    ['code' => '090195', 'name' => 'Gowans MFB'],
    ['code' => '090196', 'name' => 'OK MFB'],
    ['code' => '090197', 'name' => 'Spartan MFB'],
    ['code' => '090198', 'name' => 'FCT MFB'],
    ['code' => '090205', 'name' => 'New Prudential Bank'],
    ['code' => '090251', 'name' => 'UNN MFB'],
    ['code' => '090252', 'name' => 'Yobe MFB'],
    ['code' => '090254', 'name' => 'Coastline MFB'],
    ['code' => '090258', 'name' => 'Innovectives Kesh'],
    ['code' => '090259', 'name' => 'FUTO MFB'],
    ['code' => '090260', 'name' => 'ASOSavings'],
    ['code' => '090262', 'name' => 'Corestep MFB'],
    ['code' => '090263', 'name' => 'FBN Mortgages Limited'],
    ['code' => '090264', 'name' => 'Uzondu MFB'],
    ['code' => '090265', 'name' => 'Aztec MFB'],
    ['code' => '090266', 'name' => 'Kenechukwu MFB'],
    ['code' => '090267', 'name' => 'AKU MFB'],
    ['code' => '090268', 'name' => 'Ibeto MFB'],
    ['code' => '090269', 'name' => 'Chukwunenye MFB'],
    ['code' => '090270', 'name' => 'GMB MFB'],
    ['code' => '090271', 'name' => 'Rehoboth MFB'],
    ['code' => '090272', 'name' => 'Giant Stride MFB'],
    ['code' => '090273', 'name' => 'Anchorage MFB'],
    ['code' => '090274', 'name' => 'Light MFB'],
    ['code' => '090275', 'name' => 'Cloverleaf MFB'],
    ['code' => '090276', 'name' => 'Apple MFB'],
    ['code' => '090277', 'name' => 'Fame MFB'],
    ['code' => '090278', 'name' => 'Kayvee MFB'],
    ['code' => '090279', 'name' => 'Baobab MFB'],
    ['code' => '090280', 'name' => 'Mainland MFB'],
    ['code' => '090281', 'name' => 'Rigo MFB'],
    ['code' => '090282', 'name' => 'OAU MFB'],
    ['code' => '090283', 'name' => 'Mautech MFB'],
    ['code' => '090284', 'name' => 'Lifegate MFB'],
    ['code' => '090285', 'name' => 'Ally MFB'],
    ['code' => '090286', 'name' => 'Unilag MFB'],
    ['code' => '090287', 'name' => 'Udu MFB'],
    ['code' => '090289', 'name' => 'Solid Allianze MFB'],
    ['code' => '090290', 'name' => 'Olowolagba MFB'],
    ['code' => '090291', 'name' => 'Oluyole MFB'],
    ['code' => '090292', 'name' => 'Nasarawa MFB'],
    ['code' => '090293', 'name' => 'Okpoga MFB'],
    ['code' => '090294', 'name' => 'Ospoly MFB'],
    ['code' => '090295', 'name' => 'Nice MFB'],
    ['code' => '090296', 'name' => 'Oyan MFB'],
    ['code' => '090297', 'name' => 'UniCal MFB'],
    ['code' => '090298', 'name' => 'Bipc MFB'],
    ['code' => '090299', 'name' => 'Isaleoyo MFB'],
    ['code' => '090300', 'name' => 'EWT MFB'],
    ['code' => '090302', 'name' => 'IMO MFB'],
    ['code' => '090303', 'name' => 'Anchoria MFB'],
    ['code' => '090304', 'name' => 'Brightness MFB'],
    ['code' => '090305', 'name' => 'Tsanyawa MFB'],
    ['code' => '090306', 'name' => 'Crescent MFB'],
    ['code' => '090307', 'name' => 'Olomore MFB'],
    ['code' => '090308', 'name' => 'Gabsyn MFB'],
    ['code' => '090309', 'name' => 'Avuenegbe MFB'],
    ['code' => '090310', 'name' => 'Ekondo MFB'],
    ['code' => '090311', 'name' => 'Evergreen MFB'],
    ['code' => '090312', 'name' => 'Ada MFB'],
    ['code' => '090313', 'name' => 'Ishie MFB'],
    ['code' => '090314', 'name' => 'Ceibs MFB'],
    ['code' => '090315', 'name' => 'Kogi MFB'],
    ['code' => '090316', 'name' => 'Stanford MFB'],
    ['code' => '090317', 'name' => 'First Royal MFB'],
    ['code' => '090318', 'name' => 'First Option MFB'],
    ['code' => '090319', 'name' => 'Safe Haven MFB'],
    ['code' => '090320', 'name' => 'Assets MFB'],
    ['code' => '090321', 'name' => 'Verite MFB'],
    ['code' => '090322', 'name' => 'Gigisya MFB'],
    ['code' => '090323', 'name' => 'Preeminent MFB'],
    ['code' => '090324', 'name' => 'Pennywise MFB'],
    ['code' => '090325', 'name' => 'Gowans MFB'],
    ['code' => '090326', 'name' => 'Suave MFB'],
    ['code' => '090327', 'name' => 'Rima Growth MFB'],
    ['code' => '090328', 'name' => 'Solidrock MFB'],
    ['code' => '090329', 'name' => 'M36'],
    ['code' => '090330', 'name' => 'Gti MFB'],
    ['code' => '090331', 'name' => 'Bencrest MFB'],
    ['code' => '090332', 'name' => 'AcreSAL MFB'],
    ['code' => '090333', 'name' => 'Moneyfield MFB'],
    ['code' => '090334', 'name' => 'Cvf MFB'],
    ['code' => '090335', 'name' => 'Peak MFB'],
    ['code' => '090336', 'name' => 'BIPC MFB'],
    ['code' => '090337', 'name' => 'Fims MFB'],
    ['code' => '090338', 'name' => 'Coastline MFB'],
    ['code' => '090339', 'name' => 'Glory MFB'],
    ['code' => '090340', 'name' => 'Ibu-Aje MFB'],
    ['code' => '090341', 'name' => 'Richest MFB'],
    ['code' => '090342', 'name' => 'Pristine Divitis MFB'],
    ['code' => '090343', 'name' => 'Gmb MFB'],
    ['code' => '090345', 'name' => 'OAU MFB'],
    ['code' => '090346', 'name' => 'Rigo MFB'],
    ['code' => '090347', 'name' => 'Mgbidi MFB'],
    ['code' => '090348', 'name' => 'Goodnews MFB'],
    ['code' => '090349', 'name' => 'Citizen Trust MFB'],
    ['code' => '090350', 'name' => 'Nwannegadi MFB'],
    ['code' => '090351', 'name' => 'Hidefin MFB'],
    ['code' => '090352', 'name' => 'Richway MFB'],
    ['code' => '090353', 'name' => 'COSL MFB'],
    ['code' => '090354', 'name' => 'Solutions MFB'],
    ['code' => '090355', 'name' => 'Trustfund MFB'],
    ['code' => '090356', 'name' => 'Wellness MFB'],
    ['code' => '090357', 'name' => 'New Dawn MFB'],
    ['code' => '090358', 'name' => 'Lavender MFB'],
    ['code' => '090359', 'name' => 'Ethics MFB'],
    ['code' => '090360', 'name' => 'Kredi MFB'],
    ['code' => '090361', 'name' => 'Maintrust MFB'],
    ['code' => '090362', 'name' => 'Yct MFB'],
    ['code' => '090363', 'name' => 'Iyin Ekiti MFB'],
    ['code' => '090364', 'name' => 'Unilorin MFB'],
    ['code' => '090365', 'name' => 'Kadpoly MFB'],
    ['code' => '090366', 'name' => 'Akuchukwu MFB'],
    ['code' => '090367', 'name' => 'Cks MFB'],
    ['code' => '090368', 'name' => 'Olabisi Onabanjo University MFB'],
    ['code' => '090369', 'name' => 'Sunbeam MFB'],
    ['code' => '090370', 'name' => 'Kwasu MFB'],
    ['code' => '090371', 'name' => 'Sulspap MFB'],
    ['code' => '090372', 'name' => 'Fortis MFB'],
    ['code' => '090373', 'name' => 'Kings MFB'],
    ['code' => '090374', 'name' => 'Ilasan MFB'],
    ['code' => '090375', 'name' => 'Uzondu MFB'],
    ['code' => '090376', 'name' => 'Parkway MFB'],
    ['code' => '090377', 'name' => 'Rockshield MFB'],
    ['code' => '090378', 'name' => 'TASUED MFB'],
    ['code' => '090379', 'name' => 'Fedpoly Nasarawa MFB'],
    ['code' => '090380', 'name' => 'Waya MFB'],
    ['code' => '090381', 'name' => 'Gombe MFB'],
    ['code' => '090382', 'name' => 'Stein MFB'],
    ['code' => '090383', 'name' => 'Ibeto MFB'],
    ['code' => '090384', 'name' => 'Polyibadan MFB'],
    ['code' => '090385', 'name' => 'Rehoboth MFB'],
    ['code' => '090386', 'name' => 'Giant Stride MFB'],
    ['code' => '090387', 'name' => 'Taj Bank MFB'],
    ['code' => '090388', 'name' => 'Sincere MFB'],
    ['code' => '090389', 'name' => 'Excellent MFB'],
    ['code' => '090390', 'name' => 'Giwa MFB'],
    ['code' => '090391', 'name' => 'Ilaro Poly MFB'],
    ['code' => '090392', 'name' => 'VFD MFB'],
    ['code' => '090393', 'name' => 'Uzondu MFB'],
    ['code' => '090394', 'name' => 'Boji Boji MFB'],
    ['code' => '090395', 'name' => 'Nasarawa MFB'],
    ['code' => '090396', 'name' => 'EWT MFB'],
    ['code' => '090397', 'name' => 'Mint MFB'],
    ['code' => '090398', 'name' => 'FSTC MFB'],
    ['code' => '090399', 'name' => 'Legend MFB'],
    ['code' => '090400', 'name' => 'Federal Polytechnic Oko MFB'],
    ['code' => '090401', 'name' => 'Fedpoffa MFB'],
    ['code' => '090402', 'name' => 'Calabar MFB'],
    ['code' => '090403', 'name' => 'Unimaid MFB'],
    ['code' => '090404', 'name' => 'Ndeaboh MFB'],
    ['code' => '090405', 'name' => 'Alekun MFB'],
    ['code' => '090406', 'name' => 'Isuofia MFB'],
    ['code' => '090407', 'name' => 'Al-Barakah MFB'],
    ['code' => '090408', 'name' => 'Asha MFB'],
    ['code' => '090409', 'name' => 'Wudil MFB'],
    ['code' => '090410', 'name' => 'Hala MFB'],
    ['code' => '090411', 'name' => 'Afemai MFB'],
    ['code' => '090412', 'name' => 'Aku MFB'],
    ['code' => '090413', 'name' => 'Iperu MFB'],
    ['code' => '090414', 'name' => 'Gbede MFB'],
    ['code' => '090415', 'name' => 'New Prudential MFB'],
    ['code' => '090416', 'name' => 'Bokkos MFB'],
    ['code' => '090417', 'name' => 'Mgbidi MFB'],
    ['code' => '090418', 'name' => 'Sim MFB'],
    ['code' => '090419', 'name' => 'Iyamoye MFB'],
    ['code' => '090420', 'name' => 'Ijare MFB'],
    ['code' => '090421', 'name' => 'Otuo MFB'],
    ['code' => '090422', 'name' => 'Ilesa MFB'],
    ['code' => '090423', 'name' => 'Oraukwu MFB'],
    ['code' => '090424', 'name' => 'Ile-Oluji MFB'],
    ['code' => '090425', 'name' => 'Ilora MFB'],
    ['code' => '090426', 'name' => 'Oke-Aro MFB'],
    ['code' => '090427', 'name' => 'Ifedapo MFB'],
    ['code' => '090428', 'name' => 'Rama MFB'],
    ['code' => '090429', 'name' => 'Mautech MFB'],
    ['code' => '090430', 'name' => 'Olabisi Onabanjo University MFB'],
    ['code' => '090431', 'name' => 'Babcock University MFB'],
    ['code' => '090432', 'name' => 'Pan African MFB'],
    ['code' => '090433', 'name' => 'Corestep MFB'],
    ['code' => '090434', 'name' => 'Boji Boji MFB'],
    ['code' => '090435', 'name' => 'Iyin Ekiti MFB'],
    ['code' => '090436', 'name' => 'FSTC MFB'],
    ['code' => '090437', 'name' => 'Kadpoly MFB'],
    ['code' => '090438', 'name' => 'Lagos Building Investment Company (LBIC) MFB'],
    ['code' => '090439', 'name' => 'Adeyemi College of Education MFB'],
    ['code' => '090440', 'name' => 'Fedpoly Bauchi MFB'],
    ['code' => '090441', 'name' => 'Fedpoly Idah MFB'],
    ['code' => '090442', 'name' => 'Fedpoly Ilaro MFB'],
    ['code' => '090443', 'name' => 'Fedpoly Mubi MFB'],
    ['code' => '090444', 'name' => 'Fedpoly Nekede MFB'],
    ['code' => '090445', 'name' => 'Fedpoly Offa MFB'],
    ['code' => '090446', 'name' => 'Fedpoly Oko MFB'],
    ['code' => '090447', 'name' => 'Fedpoly Unwana MFB'],
    ['code' => '090448', 'name' => 'Gateway MFB'],
    ['code' => '090449', 'name' => 'Gboko MFB'],
    ['code' => '090450', 'name' => 'Goodluck MFB'],
    ['code' => '090451', 'name' => 'Imo State University MFB'],
    ['code' => '090452', 'name' => 'Kogi State University MFB'],
    ['code' => '090453', 'name' => 'Nasarawa State University MFB'],
    ['code' => '090454', 'name' => 'Ondo State University MFB'],
    ['code' => '090455', 'name' => 'Plateau State University MFB'],
    ['code' => '090456', 'name' => 'Tai Solarin University MFB'],
    ['code' => '090457', 'name' => 'University of Abuja MFB'],
    ['code' => '090458', 'name' => 'University of Benin MFB'],
    ['code' => '090459', 'name' => 'University of Lagos MFB'],
    ['code' => '090460', 'name' => 'University of Maiduguri MFB'],
    ['code' => '090461', 'name' => 'University of Nigeria MFB'],
    ['code' => '090462', 'name' => 'University of Port Harcourt MFB'],
    ['code' => '090463', 'name' => 'University of Uyo MFB'],
    ['code' => '090464', 'name' => 'Usmanu Danfodiyo University MFB'],
    ['code' => '090465', 'name' => 'Yobe State University MFB'],
    ['code' => '090466', 'name' => 'ABU MFB'],
    ['code' => '090467', 'name' => 'ATBU MFB'],
    ['code' => '090468', 'name' => 'BUK MFB'],
    ['code' => '090469', 'name' => 'COOU MFB'],
    ['code' => '090470', 'name' => 'CRUTECH MFB'],
    ['code' => '090471', 'name' => 'DELSU MFB'],
    ['code' => '090472', 'name' => 'ESUT MFB'],
    ['code' => '090473', 'name' => 'FUAM MFB'],
    ['code' => '090474', 'name' => 'FUDMA MFB'],
    ['code' => '090475', 'name' => 'FUGASHUA MFB'],
    ['code' => '090476', 'name' => 'FUTO MFB'],
    ['code' => '090477', 'name' => 'Gombe State University MFB'],
    ['code' => '090478', 'name' => 'IBBU MFB'],
    ['code' => '090479', 'name' => 'Ibrahim Badamasi Babangida University MFB'],
    ['code' => '090480', 'name' => 'KASU MFB'],
    ['code' => '090481', 'name' => 'KSU MFB'],
    ['code' => '090482', 'name' => 'Kwara State University MFB'],
    ['code' => '090483', 'name' => 'LAUTECH MFB'],
    ['code' => '090484', 'name' => 'MAUTECH MFB'],
    ['code' => '090485', 'name' => 'Olabisi Onabanjo University MFB'],
    ['code' => '090486', 'name' => 'OOU MFB'],
    ['code' => '090487', 'name' => 'OSUSTECH MFB'],
    ['code' => '090488', 'name' => 'Rivers State University MFB'],
    ['code' => '090489', 'name' => 'TASUED MFB'],
    ['code' => '090490', 'name' => 'UMYU MFB'],
    ['code' => '090491', 'name' => 'UNAAB MFB'],
    ['code' => '090492', 'name' => 'UNIMAID MFB'],
    ['code' => '090493', 'name' => 'UNIPORT MFB'],
    ['code' => '090494', 'name' => 'UNIZIK MFB'],
    ['code' => '090495', 'name' => 'UNN MFB'],

    // Fintech / Digital Banks / Payment Service Banks
    ['code' => '100', 'name' => 'Opay (Paycom)'],
    ['code' => '101', 'name' => 'Kuda Bank (Kuda MFB)'],
    ['code' => '100004', 'name' => 'PalmPay'],
    ['code' => '100005', 'name' => 'Moniepoint MFB'],
    ['code' => '100006', 'name' => 'Carbon (Paylater)'],
    ['code' => '100007', 'name' => 'FairMoney MFB'],
    ['code' => '100008', 'name' => 'Eyowo'],
    ['code' => '100009', 'name' => 'Fundquest'],
    ['code' => '100010', 'name' => 'Fortis Mobile'],
    ['code' => '100011', 'name' => 'GoMoney'],
    ['code' => '100012', 'name' => 'PayAttitude Online'],
    ['code' => '100013', 'name' => 'Parkway-ReadyCash'],
    ['code' => '100014', 'name' => 'RenMoney MFB'],
    ['code' => '100015', 'name' => 'Page MFBank'],
    ['code' => '100016', 'name' => 'Mint-Finex MFB'],
    ['code' => '100017', 'name' => 'ACCION MFB'],
    ['code' => '100018', 'name' => 'Rephidim Microfinance Bank'],
    ['code' => '100019', 'name' => 'FET'],
    ['code' => '100020', 'name' => 'Paycom (OPay)'],
    ['code' => '100021', 'name' => 'XSLNCE Microfinance Bank'],
    ['code' => '100022', 'name' => 'QuickFund MFB'],
    ['code' => '100023', 'name' => 'Hedonmark'],
    ['code' => '100024', 'name' => 'TagPay'],
    ['code' => '100025', 'name' => 'Tangerine Money'],
    ['code' => '100026', 'name' => 'ReadyCash (Parkway)'],
    ['code' => '100027', 'name' => 'Rubies MFB'],
    ['code' => '100028', 'name' => 'Sparkle'],
    ['code' => '100029', 'name' => 'Mint'],
    ['code' => '100030', 'name' => 'Kredi Money MFB LTD'],
    ['code' => '100031', 'name' => 'Links MFB'],
    ['code' => '100032', 'name' => 'Waya (ChamsMobile)'],
    ['code' => '100033', 'name' => 'FBNQuest Merchant Bank'],
    ['code' => '100034', 'name' => 'CashConnect MFB'],
    ['code' => '100035', 'name' => 'NowNow (NNB)'],
    ['code' => '100036', 'name' => 'ORIT MFB'],
    ['code' => '100037', 'name' => 'RAND Merchant Bank'],
    ['code' => '100038', 'name' => 'Bank3D'],
    ['code' => '100039', 'name' => 'ASO Savings'],
    ['code' => '100040', 'name' => 'Terra Kulture'],
    ['code' => '100041', 'name' => 'Kudimoney MFB'],
    ['code' => '100042', 'name' => 'Dot Microfinance Bank'],
    ['code' => '100043', 'name' => 'Branch International Finance'],
    ['code' => '100044', 'name' => 'PiggyBank/ PiggyVest'],
    ['code' => '100045', 'name' => 'Coronation Merchant Bank'],
    ['code' => '100046', 'name' => 'Nova Merchant Bank'],
    ['code' => '100047', 'name' => 'Nigeria Police Force MFB'],
    ['code' => '100048', 'name' => 'SunTrust Bank (Now Providus)'],
    ['code' => '100049', 'name' => 'Chapel Hill Denham MFB'],
    ['code' => '100050', 'name' => 'M36'],
    ['code' => '100051', 'name' => 'Grooming MFB'],
    ['code' => '100052', 'name' => 'Kuda Microfinance Bank'],
    ['code' => '100053', 'name' => 'Bowen Microfinance Bank'],
    ['code' => '100054', 'name' => 'VFD MFB'],
    ['code' => '100055', 'name' => 'eTranzact'],
    ['code' => '100056', 'name' => 'Fidelity Mobile'],
    ['code' => '100057', 'name' => 'MoneyBox'],
    ['code' => '100058', 'name' => 'Pagatech'],
    ['code' => '100059', 'name' => 'Interswitch'],
    ['code' => '100060', 'name' => 'E-Transact'],
    ['code' => '100061', 'name' => 'Quickteller'],
    ['code' => '100062', 'name' => 'SystemSpecs (Remita)'],
    ['code' => '100063', 'name' => 'FET'],
    ['code' => '100064', 'name' => 'Cellulant'],
    ['code' => '100065', 'name' => 'FSDH Merchant Bank'],
    ['code' => '100066', 'name' => 'Paga'],
    ['code' => '100067', 'name' => 'Paystack-Titan'],
    ['code' => '100068', 'name' => 'Safe Haven MFB'],
    ['code' => '100069', 'name' => 'Spectra'],
    ['code' => '100070', 'name' => 'Parralex'],
    ['code' => '100071', 'name' => 'Globus Bank'],
    ['code' => '100072', 'name' => 'Titan Bank (Paystack)'],
    ['code' => '100073', 'name' => 'Hackman Microfinance Bank'],
    ['code' => '100074', 'name' => 'Oyo State Microfinance Bank'],
    ['code' => '100075', 'name' => 'FLexNaira'],
    ['code' => '100076', 'name' => 'Mutual Trust Microfinance Bank'],
    ['code' => '100077', 'name' => 'NIRSAL Microfinance Bank'],
    ['code' => '100078', 'name' => 'Pennywise Microfinance Bank'],
    ['code' => '100079', 'name' => 'Personal Trust Microfinance Bank'],
    ['code' => '100080', 'name' => 'Microcred Microfinance Bank'],
    ['code' => '100081', 'name' => 'Baobab Microfinance Bank'],
    ['code' => '100082', 'name' => 'Refuge Mortgage Bank'],
    ['code' => '100083', 'name' => 'Page Financials'],
    ['code' => '100084', 'name' => 'FBN Mortgages Limited'],
    ['code' => '100085', 'name' => 'Abbey Mortgage Bank'],
    ['code' => '100086', 'name' => 'Platinum Mortgage Bank'],
    ['code' => '100087', 'name' => 'Lagos Building Investment Company'],
    ['code' => '100088', 'name' => 'Safetrust Mortgage Bank'],
    ['code' => '100089', 'name' => 'Jubilee-Life Mortgage Bank'],
    ['code' => '100090', 'name' => 'Infinity Trust Mortgage Bank'],
    ['code' => '100091', 'name' => 'First Generation Mortgage Bank'],
    ['code' => '100092', 'name' => 'Brent Mortgage Bank'],
    ['code' => '100093', 'name' => 'Living Trust Mortgage Bank'],
    ['code' => '100094', 'name' => 'Omoluabi Mortgage Bank'],
    ['code' => '100095', 'name' => 'MayFresh Mortgage Bank'],
    ['code' => '100096', 'name' => 'Resort Savings & Loans'],
    ['code' => '100097', 'name' => 'Gateway Mortgage Bank'],
    ['code' => '100098', 'name' => 'Century Mortgage Bank'],
    ['code' => '100099', 'name' => 'Haggai Mortgage Bank'],
    ['code' => '100100', 'name' => 'Nigeria Police Force MFB'],
    ['code' => '100101', 'name' => 'Boctrust Microfinance Bank'],
    ['code' => '100102', 'name' => 'Wetland Microfinance Bank'],
    ['code' => '100103', 'name' => 'Medef Microfinance Bank'],
    ['code' => '100104', 'name' => 'Branch International Financial Services'],
    ['code' => '100105', 'name' => 'Raven Microfinance Bank'],
    ['code' => '100106', 'name' => 'CASHCONNECT MICROFINANCE BANK'],
    ['code' => '100107', 'name' => 'NNEW WOMEN MICROFINANCE BANK'],
    ['code' => '100108', 'name' => 'OAKLAND MICROFINANCE BANK'],
    ['code' => '100109', 'name' => 'CEMCS Microfinance Bank'],
    ['code' => '100110', 'name' => '9 Payment Service Bank (9PSB)'],
    ['code' => '100111', 'name' => 'HopePSB (Payment Service Bank)'],
    ['code' => '100112', 'name' => 'MOMO PSB (Payment Service Bank)'],
    ['code' => '100113', 'name' => 'SmartCash PSB (Payment Service Bank)'],
    ['code' => '100114', 'name' => 'NOWNOW DIGITAL SYSTEMS LIMITED'],
    ['code' => '100115', 'name' => 'MANNY MICROFINANCE BANK'],
    ['code' => '100116', 'name' => 'Uhuru Microfinance Bank'],
    ['code' => '100117', 'name' => 'Molusi Microfinance Bank'],
    ['code' => '100118', 'name' => 'PalmPay Limited'],
    ['code' => '100119', 'name' => 'Nomba (Kudi) MFB'],
    ['code' => '100120', 'name' => 'Finca Microfinance Bank Limited'],
    ['code' => '100121', 'name' => 'Waya Microfinance Bank'],
    ['code' => '100122', 'name' => 'Sparkle MFB'],
    ['code' => '100123', 'name' => 'Consistent Trust Microfinance Bank'],
    ['code' => '100124', 'name' => 'CCT MFB'],
    ['code' => '100125', 'name' => 'Firmus MFB'],
    ['code' => '100126', 'name' => 'Peace Microfinance Bank'],
    ['code' => '100127', 'name' => 'Oloja Microfinance Bank'],
    ['code' => '100128', 'name' => 'Bankly MFB'],
    ['code' => '100129', 'name' => 'Payday'],
    ['code' => '100130', 'name' => 'Aramoko MFB'],
    ['code' => '100131', 'name' => 'Akwa Savings & Loans Limited'],
    ['code' => '100132', 'name' => 'Alert MFB'],
    ['code' => '100133', 'name' => 'Fedeth MFB'],
    ['code' => '100134', 'name' => 'PalmPay'],
    ['code' => '100135', 'name' => 'VFD MFB'],
    ['code' => '100136', 'name' => 'IBANK MFB'],
    ['code' => '100137', 'name' => 'Imperial Homes Mortgage Bank'],
    ['code' => '100138', 'name' => 'Millennium MFB'],
    ['code' => '100139', 'name' => 'Vas2nets Technologies Limited'],
    ['code' => '100140', 'name' => 'Sparkle Microfinance Bank'],
    ['code' => '100141', 'name' => 'Momo Payment Service Bank'],
    ['code' => '100142', 'name' => 'Paga'],
    ['code' => '100143', 'name' => 'Bosak MFB'],
    ['code' => '100144', 'name' => 'Gbede MFB'],
    ['code' => '100145', 'name' => 'IKENNE MFB'],
    ['code' => '100146', 'name' => 'Okigwe MFB'],
    ['code' => '100147', 'name' => 'MAYFRESH MORTGAGE BANK'],
    ['code' => '100148', 'name' => 'FOCUS MFB'],
    ['code' => '100149', 'name' => 'ISS MFB'],
    ['code' => '100150', 'name' => 'ILISAN MFB'],
    ['code' => '100151', 'name' => 'E-BARCS MFB'],
    ['code' => '100152', 'name' => 'Goodnews Microfinance Bank'],
    ['code' => '100153', 'name' => 'Fina Trust Microfinance Bank'],
    ['code' => '100154', 'name' => 'Petra Microfinance Bank'],
    ['code' => '100155', 'name' => 'Support MFB'],
    ['code' => '100156', 'name' => 'AMBASSADORS MFB'],
    ['code' => '100157', 'name' => 'Moyofade MFB'],
    ['code' => '100158', 'name' => 'OYAN MFB'],
    ['code' => '100159', 'name' => 'RIGO MFB'],
    ['code' => '100160', 'name' => 'CROSSRIVER MICROFINANCE BANK'],
    ['code' => '100161', 'name' => 'FEDERAL POLYTECHNIC NEKEDE MFB'],
    ['code' => '100162', 'name' => 'MAINLAND MFB'],
    ['code' => '100163', 'name' => 'GBOKO MFB'],
    ['code' => '100164', 'name' => 'YCT MFB'],
    ['code' => '100165', 'name' => 'UNIPORT MFB'],
    ['code' => '100166', 'name' => 'RAND MERCHANT BANK'],
    ['code' => '100167', 'name' => 'NOWNOW'],
    ['code' => '100168', 'name' => 'FORTIS MFB'],
    ['code' => '100169', 'name' => 'KREDI MONEY MFB'],
    ['code' => '100170', 'name' => 'GIGINYA MFB'],
    ['code' => '100171', 'name' => 'GMB MFB'],
    ['code' => '100172', 'name' => 'SMARTCASH PAYMENT SERVICE BANK'],
    ['code' => '100173', 'name' => 'HOPEPSB'],
    ['code' => '100174', 'name' => 'CITIZEN TRUST MFB'],
    ['code' => '100175', 'name' => 'TANGERINE MONEY'],
    ['code' => '100176', 'name' => 'M36'],
    ['code' => '100177', 'name' => 'HEADQUARTERS MFB'],
    ['code' => '100178', 'name' => 'FEDERAL UNIVERSITY DUTSE MFB'],
    ['code' => '100179', 'name' => 'FEDERAL UNIVERSITY WUKARI MFB'],
    ['code' => '100180', 'name' => 'FEDERAL UNIVERSITY LAFIA MFB'],
    ['code' => '100181', 'name' => 'FEDERAL UNIVERSITY GASHUA MFB'],
    ['code' => '100182', 'name' => 'FEDERAL UNIVERSITY BIRNIN KEBBI MFB'],
    ['code' => '100183', 'name' => 'FEDERAL UNIVERSITY GUSAU MFB'],
    ['code' => '100184', 'name' => 'FEDERAL UNIVERSITY KASHERE MFB'],
    ['code' => '100185', 'name' => 'FEDERAL UNIVERSITY LOKOJA MFB'],
    ['code' => '100186', 'name' => 'FEDERAL UNIVERSITY OTUOKE MFB'],
    ['code' => '100187', 'name' => 'FEDERAL UNIVERSITY OYE-EKITI MFB'],
    ['code' => '100188', 'name' => '100188'],
    ['code' => '100189', 'name' => 'FEDERAL UNIVERSITY NDUFU-ALIKE MFB'],
    ['code' => '100190', 'name' => 'FEDERAL UNIVERSITY DUTSIN-MA MFB'],
    ['code' => '100191', 'name' => 'FEDERAL UNIVERSITY TARABA MFB'],
    ['code' => '100192', 'name' => 'FEDERAL POLYTECHNIC ADO-EKITI MFB'],
    ['code' => '100193', 'name' => 'FEDERAL POLYTECHNIC BIDA MFB'],
    ['code' => '100194', 'name' => 'FEDERAL POLYTECHNIC EDE MEDICAL MFB'],
    ['code' => '100195', 'name' => 'FEDERAL POLYTECHNIC KAURA NAMODA MFB'],
    ['code' => '100196', 'name' => 'FEDERAL POLYTECHNIC UKANA MFB'],
    ['code' => '100197', 'name' => 'FEDERAL COLLEGE OF EDUCATION MFB'],
    ['code' => '100198', 'name' => 'FEDERAL COLLEGE OF EDUCATION (TECH) MFB'],
    ['code' => '100199', 'name' => 'ALVANA MICROFINANCE BANK'],
    ['code' => '100200', 'name' => 'TRIPLE A MICROFINANCE BANK'],
    ['code' => '100201', 'name' => 'OLOJA MFB'],
    ['code' => '100202', 'name' => 'ABUCOOP MFB'],
    ['code' => '100203', 'name' => 'GREAT STEP MFB'],
    ['code' => '100204', 'name' => 'VITA GREEN MICROFINANCE BANK'],
    ['code' => '100205', 'name' => 'APEKS MICROFINANCE BANK'],
    ['code' => '100206', 'name' => 'AVUNEGWU MFB'],
    ['code' => '100207', 'name' => 'AUCHI POLY MFB'],
    ['code' => '100208', 'name' => 'LAPO MFB'],
    ['code' => '100209', 'name' => 'SEED CAPITAL MFB'],
    ['code' => '100210', 'name' => 'JESSEFIELD MFB'],
    ['code' => '100211', 'name' => 'NWANNEKA MFB'],
    ['code' => '100212', 'name' => 'BOSAK MFB'],
    ['code' => '100213', 'name' => 'IKENNE MFB'],
    ['code' => '100214', 'name' => 'ELLIS MFB'],
    ['code' => '100215', 'name' => 'FRONTIER MFB'],
    ['code' => '100216', 'name' => 'KENECHUKWU MFB'],
    ['code' => '100217', 'name' => 'ORITA BASORUN MFB'],
    ['code' => '100218', 'name' => 'APEX MFB'],
    ['code' => '100219', 'name' => 'OSPOLY MFB'],
    ['code' => '100220', 'name' => 'MACROD MFB'],
    ['code' => '100221', 'name' => 'AL-BARAKAH MFB'],
    ['code' => '100222', 'name' => 'LAVENDER MFB'],
    ['code' => '100223', 'name' => 'WUDIL MFB'],
    ['code' => '100224', 'name' => 'FIRST GEN MFB'],
    ['code' => '100225', 'name' => 'FCT MFB'],
    ['code' => '100226', 'name' => 'ALVANA MFB'],
    ['code' => '100227', 'name' => 'TRUSTFUND MFB'],
    ['code' => '100228', 'name' => 'RICHWAY MFB'],
    ['code' => '100229', 'name' => 'IKOYI-OSUN MFB'],
    ['code' => '100230', 'name' => 'ISUOFIA MFB'],
    ['code' => '100231', 'name' => 'POLYIBADAN MFB'],
    ['code' => '100232', 'name' => 'REHOBOTH MFB'],
    ['code' => '100233', 'name' => 'MGBIDI MFB'],
    ['code' => '100234', 'name' => 'GBEDU MFB'],
    ['code' => '100235', 'name' => 'CHUKWUNENYE MFB'],
    ['code' => '100236', 'name' => 'ALEX MFB'],
    ['code' => '100237', 'name' => 'FAME MFB'],
    ['code' => '100238', 'name' => 'FEDERAL UNIVERSITY OTUOKE MFB'],
    ['code' => '100239', 'name' => 'UNILORIN MFB'],
    ['code' => '100240', 'name' => 'ABSU MFB'],
    ['code' => '100241', 'name' => 'REPHIDIM MFB'],
    ['code' => '100242', 'name' => 'RICHEST MFB'],
    ['code' => '100243', 'name' => 'GBEDU MFB'],
    ['code' => '100244', 'name' => 'IKOYI MFB'],
    ['code' => '100245', 'name' => 'FIMS MFB'],
    ['code' => '100246', 'name' => 'EMPIRE TRUST MFB'],
    ['code' => '100247', 'name' => 'EDFIN MFB'],
    ['code' => '100248', 'name' => 'NWANNEKA MFB'],
    ['code' => '100249', 'name' => 'ARISE MFB'],
    ['code' => '100250', 'name' => 'OMIYE MFB'],
    ['code' => '100251', 'name' => 'E-TRANZACT'],
    ['code' => '100252', 'name' => 'INTERSWITCH'],
    ['code' => '100253', 'name' => 'QUICKTELLER'],
    ['code' => '100254', 'name' => 'SYSTEMSPECS'],
    ['code' => '100255', 'name' => 'CEMCS MFB'],
    ['code' => '100256', 'name' => 'TITAN TRUST BANK'],
    ['code' => '100257', 'name' => 'GLOBUS BANK'],
    ['code' => '100258', 'name' => 'WEMA BANK'],
    ['code' => '100259', 'name' => 'UNITY BANK'],
    ['code' => '100260', 'name' => 'POLARIS BANK'],
    ['code' => '100261', 'name' => 'PROVIDUSBANK'],
    ['code' => '100262', 'name' => 'SUNTRUST BANK'],
    ['code' => '100263', 'name' => 'JAIZ BANK'],
    ['code' => '100264', 'name' => 'KEYSTONE BANK'],
    ['code' => '100265', 'name' => 'FIRST CITY MONUMENT BANK (FCMB)'],
    ['code' => '100266', 'name' => 'FIDELITY BANK'],
    ['code' => '100267', 'name' => 'ECOBANK NIGERIA'],
    ['code' => '100268', 'name' => 'ACCESS BANK'],
    ['code' => '100269', 'name' => 'STANDARD CHARTERED BANK'],
    ['code' => '100270', 'name' => 'UNION BANK'],
    ['code' => '100271', 'name' => 'STERLING BANK'],
    ['code' => '100272', 'name' => 'FIRST BANK OF NIGERIA'],
    ['code' => '100273', 'name' => 'GUARANTY TRUST BANK (GTB)'],
    ['code' => '100274', 'name' => 'ZENITH BANK'],
    ['code' => '100275', 'name' => 'UNITED BANK FOR AFRICA (UBA)'],
    ['code' => '100276', 'name' => 'ENTERPRISE BANK'],
    ['code' => '100277', 'name' => 'MAINSTREET BANK'],
    ['code' => '100278', 'name' => 'HERITAGE BANK'],
    ['code' => '100279', 'name' => 'CORONATION MERCHANT BANK'],
    ['code' => '100280', 'name' => 'NOVA MERCHANT BANK'],
    ['code' => '100281', 'name' => 'FSDH MERCHANT BANK'],
    ['code' => '100282', 'name' => 'RAND MERCHANT BANK'],
    ['code' => '100283', 'name' => 'ABBey MORTGAGE BANK'],
    ['code' => '100284', 'name' => 'REFUGE MORTGAGE BANK'],
    ['code' => '100285', 'name' => 'FBN MORTGAGES LIMITED'],
    ['code' => '100286', 'name' => 'PLATINUM MORTGAGE BANK'],
    ['code' => '100287', 'name' => 'SAFETRUST MORTGAGE BANK'],
    ['code' => '100288', 'name' => 'JUBILEE-LIFE MORTGAGE BANK'],
    ['code' => '100289', 'name' => 'INFINITY TRUST MORTGAGE BANK'],
    ['code' => '100290', 'name' => 'FIRST GENERATION MORTGAGE BANK'],
    ['code' => '100291', 'name' => 'BRENT MORTGAGE BANK'],
    ['code' => '100292', 'name' => 'LIVING TRUST MORTGAGE BANK'],
    ['code' => '100293', 'name' => 'OMOLUABI MORTGAGE BANK'],
    ['code' => '100294', 'name' => 'MAYFRESH MORTGAGE BANK'],
    ['code' => '100295', 'name' => 'RESORT SAVINGS & LOANS'],
    ['code' => '100296', 'name' => 'GATEWAY MORTGAGE BANK'],
    ['code' => '100297', 'name' => 'CENTURY MORTGAGE BANK'],
    ['code' => '100298', 'name' => 'HAGGAI MORTGAGE BANK'],
    ['code' => '100299', 'name' => 'PAGE FINANCIALS'],
    ['code' => '100300', 'name' => 'ACCION MICROFINANCE BANK'],
    ['code' => '100301', 'name' => 'BANEX MICROFINANCE BANK'],
    ['code' => '100302', 'name' => 'CASHCONNECT MICROFINANCE BANK'],
    ['code' => '100303', 'name' => 'CENTRAL MFB'],
    ['code' => '100304', 'name' => 'FAST MFB'],
    ['code' => '100305', 'name' => 'FINA TRUST MICROFINANCE BANK'],
    ['code' => '100306', 'name' => 'GROOMING MICROFINANCE BANK'],
    ['code' => '100307', 'name' => 'NEW PRUDENTIAL BANK'],
    ['code' => '100308', 'name' => 'NIGERIA PRISONS MFB'],
    ['code' => '100309', 'name' => 'NIRSAL MICROFINANCE BANK'],
    ['code' => '100310', 'name' => 'NON-INTEREST BANK'],
    ['code' => '100311', 'name' => 'PATRICKGOLD MICROFINANCE BANK'],
    ['code' => '100312', 'name' => 'PENNYWISE MICROFINANCE BANK'],
    ['code' => '100313', 'name' => 'PERSONAL TRUST MICROFINANCE BANK'],
    ['code' => '100314', 'name' => 'PETRA MICROFINANCE BANK'],
    ['code' => '100315', 'name' => 'REPHIDIM MICROFINANCE BANK'],
    ['code' => '100316', 'name' => 'ROYAL EXCHANGE MICROFINANCE BANK'],
    ['code' => '100317', 'name' => 'SAGAMU MICROFINANCE BANK'],
    ['code' => '100318', 'name' => 'STELLAR MICROFINANCE BANK'],
    ['code' => '100319', 'name' => 'SUPPORT MICROFINANCE BANK'],
    ['code' => '100320', 'name' => 'TRUST MICROFINANCE BANK'],
    ['code' => '100321', 'name' => 'TRUSTBANC J6 MICROFINANCE BANK'],
    ['code' => '100322', 'name' => 'UNIBEN MICROFINANCE BANK'],
    ['code' => '100323', 'name' => 'VIRTUE MICROFINANCE BANK'],
    ['code' => '100324', 'name' => 'XSLNCE MICROFINANCE BANK'],
    ['code' => '100325', 'name' => 'YES MICROFINANCE BANK'],
    ['code' => '100326', 'name' => 'ADDOSSER MICROFINANCE BANK'],
    ['code' => '100327', 'name' => 'AL-BARAKAH MICROFINANCE BANK'],
    ['code' => '100328', 'name' => 'ASSETS MICROFINANCE BANK'],
    ['code' => '100329', 'name' => 'ASTRA POLARIS MICROFINANCE BANK'],
    ['code' => '100330', 'name' => 'BALOGUN GAMBARI MICROFINANCE BANK'],
    ['code' => '100331', 'name' => 'BOCTRUST MICROFINANCE BANK'],
    ['code' => '100332', 'name' => 'BOWEN MICROFINANCE BANK'],
    ['code' => '100333', 'name' => 'CEMCS MICROFINANCE BANK'],
    ['code' => '100334', 'name' => 'CONSUMER MICROFINANCE BANK'],
    ['code' => '100335', 'name' => 'DAYSPRING MICROFINANCE BANK'],
    ['code' => '100336', 'name' => 'EAGLE FLIGHT MICROFINANCE BANK'],
    ['code' => '100337', 'name' => 'EBSU MICROFINANCE BANK'],
    ['code' => '100338', 'name' => 'EK-Reliable MICROFINANCE BANK'],
    ['code' => '100339', 'name' => 'EMERALD MICROFINANCE BANK'],
    ['code' => '100340', 'name' => 'ENGLISH MICROFINANCE BANK'],
    ['code' => '100341', 'name' => 'ESAN MICROFINANCE BANK'],
    ['code' => '100342', 'name' => 'EVERGREEN MICROFINANCE BANK'],
    ['code' => '100343', 'name' => 'EVANGEL MICROFINANCE BANK'],
    ['code' => '100344', 'name' => 'FAST CREDIT MICROFINANCE BANK'],
    ['code' => '100345', 'name' => 'FBN MICROFINANCE BANK'],
    ['code' => '100346', 'name' => 'FCMB MICROFINANCE BANK'],
    ['code' => '100347', 'name' => 'FCT MICROFINANCE BANK'],
    ['code' => '100348', 'name' => 'FEDETH MICROFINANCE BANK'],
    ['code' => '100349', 'name' => 'FHA MICROFINANCE BANK'],
    ['code' => '100350', 'name' => 'FIRMUS MICROFINANCE BANK'],
    ['code' => '100351', 'name' => 'FORTIS MICROFINANCE BANK'],
    ['code' => '100352', 'name' => 'FSDH MICROFINANCE BANK'],
    ['code' => '100353', 'name' => 'FULL RANGE MICROFINANCE BANK'],
    ['code' => '100354', 'name' => 'FUTO MICROFINANCE BANK'],
    ['code' => '100355', 'name' => 'GATEWAY MORTGAGE BANK'],
    ['code' => '100356', 'name' => 'GIREI MICROFINANCE BANK'],
    ['code' => '100357', 'name' => 'GOWANS MICROFINANCE BANK'],
    ['code' => '100358', 'name' => 'GREENBANK MICROFINANCE BANK'],
    ['code' => '100359', 'name' => 'GTI MICROFINANCE BANK'],
    ['code' => '100360', 'name' => 'HACKMAN MICROFINANCE BANK'],
    ['code' => '100361', 'name' => 'HASAL MICROFINANCE BANK'],
    ['code' => '100362', 'name' => 'HERITAGE BANK'],
    ['code' => '100363', 'name' => 'HOLLANDALE MICROFINANCE BANK'],
    ['code' => '100364', 'name' => 'IBA MICROFINANCE BANK'],
    ['code' => '100365', 'name' => 'IBETO MICROFINANCE BANK'],
    ['code' => '100366', 'name' => 'IC GLOBAL MICROFINANCE BANK'],
    ['code' => '100367', 'name' => 'IKENNE MICROFINANCE BANK'],
    ['code' => '100368', 'name' => 'IKIRE MICROFINANCE BANK'],
    ['code' => '100369', 'name' => 'ILASAN MICROFINANCE BANK'],
    ['code' => '100370', 'name' => 'ILORA MICROFINANCE BANK'],
    ['code' => '100371', 'name' => 'ILORIN MICROFINANCE BANK'],
    ['code' => '100372', 'name' => 'IMOWO MICROFINANCE BANK'],
    ['code' => '100373', 'name' => 'IMPERIAL HOMES MORTGAGE BANK'],
    ['code' => '100374', 'name' => 'INFINITY TRUST MORTGAGE BANK'],
    ['code' => '100375', 'name' => 'INVESTMENT AND DEVELOPMENT MICROFINANCE BANK'],
    ['code' => '100376', 'name' => 'ISALEOYO MICROFINANCE BANK'],
    ['code' => '100377', 'name' => 'JUBILEE-LIFE MORTGAGE BANK'],
    ['code' => '100378', 'name' => 'KENECHUKWU MICROFINANCE BANK'],
    ['code' => '100379', 'name' => 'KONTAGORA MICROFINANCE BANK'],
    ['code' => '100380', 'name' => 'KUDA MICROFINANCE BANK'],
    ['code' => '100381', 'name' => 'LAGOS BUILDING INVESTMENT COMPANY (LBIC)'],
    ['code' => '100382', 'name' => 'LAVENDER MICROFINANCE BANK'],
    ['code' => '100383', 'name' => 'LIGHT MICROFINANCE BANK'],
    ['code' => '100384', 'name' => 'LIVING TRUST MORTGAGE BANK'],
    ['code' => '100385', 'name' => 'MAINLAND MICROFINANCE BANK'],
    ['code' => '100386', 'name' => 'MAINSTREET MICROFINANCE BANK'],
    ['code' => '100387', 'name' => 'MALACHY MICROFINANCE BANK'],
    ['code' => '100388', 'name' => 'MAMAMBILLA MICROFINANCE BANK'],
    ['code' => '100389', 'name' => 'MARCUS GARVEY MICROFINANCE BANK'],
    ['code' => '100390', 'name' => 'MAXIMUM MICROFINANCE BANK'],
    ['code' => '100391', 'name' => 'MAYFRESH MORTGAGE BANK'],
    ['code' => '100392', 'name' => 'MEGAPRAISE MICROFINANCE BANK'],
    ['code' => '100393', 'name' => 'MICROCRED MICROFINANCE BANK'],
    ['code' => '100394', 'name' => 'MICROVIS MICROFINANCE BANK'],
    ['code' => '100395', 'name' => 'MIDLAND MICROFINANCE BANK'],
    ['code' => '100396', 'name' => 'MOLUSI MICROFINANCE BANK'],
    ['code' => '100397', 'name' => 'MONEYFIELD MICROFINANCE BANK'],
    ['code' => '100398', 'name' => 'MUTUAL BENEFITS MICROFINANCE BANK'],
    ['code' => '100399', 'name' => 'MUTUAL TRUST MICROFINANCE BANK'],
    ['code' => '100400', 'name' => 'NDIORAH MICROFINANCE BANK'],
    ['code' => '100401', 'name' => 'NEW PRUDENTIAL BANK'],
    ['code' => '100402', 'name' => 'NIGERIAN NAVY MICROFINANCE BANK'],
    ['code' => '100403', 'name' => 'NIGERIAN POLICE FORCE MICROFINANCE BANK'],
    ['code' => '100404', 'name' => 'NIPOST MICROFINANCE BANK'],
    ['code' => '100405', 'name' => 'NIRSAL MICROFINANCE BANK'],
    ['code' => '100406', 'name' => 'NNEW WOMEN MICROFINANCE BANK'],
    ['code' => '100407', 'name' => 'NOVA MERCHANT BANK'],
    ['code' => '100408', 'name' => 'NOWNOW DIGITAL SYSTEMS LIMITED'],
    ['code' => '100409', 'name' => 'OAKLAND MICROFINANCE BANK'],
    ['code' => '100410', 'name' => 'OCHE MICROFINANCE BANK'],
    ['code' => '100411', 'name' => 'OHAFIA MICROFINANCE BANK'],
    ['code' => '100412', 'name' => 'OKPOGA MICROFINANCE BANK'],
    ['code' => '100413', 'name' => 'OLABISI ONABANJO UNIVERSITY MICROFINANCE BANK'],
    ['code' => '100414', 'name' => 'OLOWOLAGBA MICROFINANCE BANK'],
    ['code' => '100415', 'name' => 'OMIYE MICROFINANCE BANK'],
    ['code' => '100416', 'name' => 'OMOLUABI MICROFINANCE BANK'],
    ['code' => '100417', 'name' => 'OPAY (PAYCOM)'],
    ['code' => '100418', 'name' => 'ORITAMEFA BAPTIST MODEL SCHOOL MICROFINANCE BANK'],
    ['code' => '100419', 'name' => 'ORITA-BASORUN MICROFINANCE BANK'],
    ['code' => '100420', 'name' => 'OSPOLY MICROFINANCE BANK'],
    ['code' => '100421', 'name' => 'OTUO MICROFINANCE BANK'],
    ['code' => '100422', 'name' => 'PARKWAY MICROFINANCE BANK'],
    ['code' => '100423', 'name' => 'PARALLEX MICROFINANCE BANK'],
    ['code' => '100424', 'name' => 'PATRICKGOLD MICROFINANCE BANK'],
    ['code' => '100425', 'name' => 'PEACE MICROFINANCE BANK'],
    ['code' => '100426', 'name' => 'PENNYWISE MICROFINANCE BANK'],
    ['code' => '100427', 'name' => 'PERSONAL TRUST MICROFINANCE BANK'],
    ['code' => '100428', 'name' => 'PETRA MICROFINANCE BANK'],
    ['code' => '100429', 'name' => 'PIGGYBANK / PIGGYVEST'],
    ['code' => '100430', 'name' => 'PLATINUM MORTGAGE BANK'],
    ['code' => '100431', 'name' => 'PREEMINENT MICROFINANCE BANK'],
    ['code' => '100432', 'name' => 'PRESTIGE MICROFINANCE BANK'],
    ['code' => '100433', 'name' => 'PRUDENTIAL BANK'],
    ['code' => '100434', 'name' => 'QUICKFUND MICROFINANCE BANK'],
    ['code' => '100435', 'name' => 'RAND MERCHANT BANK'],
    ['code' => '100436', 'name' => 'REFUGE MORTGAGE BANK'],
    ['code' => '100437', 'name' => 'REGENT MICROFINANCE BANK'],
    ['code' => '100438', 'name' => 'REHOBOTH MICROFINANCE BANK'],
    ['code' => '100439', 'name' => 'RELIANCE MICROFINANCE BANK'],
    ['code' => '100440', 'name' => 'RENMONEY MICROFINANCE BANK'],
    ['code' => '100441', 'name' => 'REPHIDIM MICROFINANCE BANK'],
    ['code' => '100442', 'name' => 'RIGO MICROFINANCE BANK'],
    ['code' => '100443', 'name' => 'ROYAL EXCHANGE MICROFINANCE BANK'],
    ['code' => '100444', 'name' => 'SAFETRUST MORTGAGE BANK'],
    ['code' => '100445', 'name' => 'SAGAMU MICROFINANCE BANK'],
    ['code' => '100446', 'name' => 'SEED CAPITAL MICROFINANCE BANK'],
    ['code' => '100447', 'name' => 'SPARKLE MICROFINANCE BANK'],
    ['code' => '100448', 'name' => 'STANFORD MICROFINANCE BANK'],
    ['code' => '100449', 'name' => 'STELLAR MICROFINANCE BANK'],
    ['code' => '100450', 'name' => 'STERLING BANK'],
    ['code' => '100451', 'name' => 'SULSPAP MICROFINANCE BANK'],
    ['code' => '100452', 'name' => 'SUNBEAM MICROFINANCE BANK'],
    ['code' => '100453', 'name' => 'SUNTRUST BANK'],
    ['code' => '100454', 'name' => 'SUPPORT MICROFINANCE BANK'],
    ['code' => '100455', 'name' => 'TAGPAY'],
    ['code' => '100456', 'name' => 'TAJ BANK'],
    ['code' => '100457', 'name' => 'TANGERINE MONEY'],
    ['code' => '100458', 'name' => 'TEASY MOBILE MONEY'],
    ['code' => '100459', 'name' => 'TITAN TRUST BANK'],
    ['code' => '100460', 'name' => 'TRIDENT MICROFINANCE BANK'],
    ['code' => '100461', 'name' => 'TRUST MICROFINANCE BANK'],
    ['code' => '100462', 'name' => 'TRUSTBANC J6 MICROFINANCE BANK'],
    ['code' => '100463', 'name' => 'UBA MORTGAGE BANK'],
    ['code' => '100464', 'name' => 'UHURU MICROFINANCE BANK'],
    ['code' => '100465', 'name' => 'UNIBEN MICROFINANCE BANK'],
    ['code' => '100466', 'name' => 'UNICAL MICROFINANCE BANK'],
    ['code' => '100467', 'name' => 'UNILAG MICROFINANCE BANK'],
    ['code' => '100468', 'name' => 'UNION BANK'],
    ['code' => '100469', 'name' => 'UNITY BANK'],
    ['code' => '100470', 'name' => 'UNIVERSITY OF IBADAN MICROFINANCE BANK'],
    ['code' => '100471', 'name' => 'VERITE MICROFINANCE BANK'],
    ['code' => '100472', 'name' => 'VFD MICROFINANCE BANK'],
    ['code' => '100473', 'name' => 'VIRTUE MICROFINANCE BANK'],
    ['code' => '100474', 'name' => 'VISA MICROFINANCE BANK'],
    ['code' => '100475', 'name' => 'WEMA BANK'],
    ['code' => '100476', 'name' => 'WETLAND MICROFINANCE BANK'],
    ['code' => '100477', 'name' => 'XSLNCE MICROFINANCE BANK'],
    ['code' => '100478', 'name' => 'YCT MICROFINANCE BANK'],
    ['code' => '100479', 'name' => 'YES MICROFINANCE BANK'],
    ['code' => '100480', 'name' => 'ZENITH BANK'],
    ['code' => '100481', 'name' => 'ZENITH MORTGAGE BANK'],
    ['code' => '100482', 'name' => 'ZIK微 FINANCE BANK'],
    ['code' => '100483', 'name' => '9 PAYMENT SERVICE BANK (9PSB)'],
    ['code' => '100484', 'name' => 'HOPEPSB'],
    ['code' => '100485', 'name' => 'MOMO PSB'],
    ['code' => '100486', 'name' => 'SMARTCASH PSB'],
];

// Sort by bank name
usort($nigerian_banks, function($a, $b) {
    return strcmp($a['name'], $b['name']);
});

// Group banks by category for dropdown display
function getBankCategories() {
    return [
        'Commercial Banks' => ['Access Bank PLC','Access Bank PLC (Diamond)','Wema Bank PLC','United Bank for Africa (UBA) PLC','Union Bank of Nigeria PLC','Stanbic IBTC Bank PLC','Standard Chartered Bank Nigeria','Polaris Bank PLC','Keystone Bank PLC','Zenith Bank PLC','Guaranty Trust Bank (GTBank) PLC','First Bank of Nigeria PLC','First City Monument Bank (FCMB) PLC','Fidelity Bank PLC','Ecobank Nigeria PLC','Jaiz Bank PLC','Unity Bank PLC','ProvidusBank PLC','Titan Trust Bank PLC','Globus Bank PLC','Citibank Nigeria'],
        'Merchant Banks' => ['Coronation Merchant Bank','FSDH Merchant Bank','Nova Merchant Bank','Rand Merchant Bank'],
        'Fintech / Digital Banks' => ['Opay (Paycom)','Kuda Bank (Kuda MFB)','PalmPay','Moniepoint MFB','Carbon (Paylater)','FairMoney MFB','Eyowo','GoMoney','PayAttitude Online','RenMoney MFB','Sparkle','Branch International Finance','PiggyBank/ PiggyVest','9 Payment Service Bank (9PSB)','HopePSB (Payment Service Bank)','MOMO PSB (Payment Service Bank)','SmartCash PSB (Payment Service Bank)','Nomba (Kudi) MFB','Bankly MFB','Payday'],
        'Microfinance Banks' => ['Lapo MFB','Rubies MFB','Page MFBank','ACCION MFB','VFD MFB','Mint-Finex MFB','Rephidim Microfinance Bank','QuickFund MFB','Kredi Money MFB LTD','Links MFB','CashConnect MFB','NowNow (NNB)','Fortis MFB','Grooming MFB','Hackman Microfinance Bank','NIRSAL Microfinance Bank','Finca Microfinance Bank Limited','Waya Microfinance Bank','Consistent Trust Microfinance Bank','Firmus MFB','Peace Microfinance Bank','COSL MFB','Trustfund MFB','Kadpoly MFB','Yct MFB','Unilorin MFB','FUTO MFB','OAU MFB','Rigo MFB','Ilara MFB','Mainland MFB','Gbede MFB','BIPC MFB','Iyin Ekiti MFB','CCT MFB','LAPO MFB','Seed Capital MFB','Jessefield MFB','GMB MFB','Rehoboth MFB','Giant Stride MFB','Anchoridge MFB','Lavender MFB','Ethics MFB','Kredi MFB','Maintrust MFB','Ilasan MFB','Uzondu MFB','Parkway MFB','Rockshield MFB','TASUED MFB','Fedpoly Nasarawa MFB','Gombe MFB','Stein MFB','Ibeto MFB','Polyibadan MFB','Excellent MFB','Giwa MFB','Ilaro Poly MFB','Boji Boji MFB','EWT MFB','Mint MFB','FSTC MFB','Legend MFB','Fedpoffa MFB','Calabar MFB','Unimaid MFB','Ndeaboh MFB','Alekun MFB','Isuofia MFB','Al-Barakah MFB','Asha MFB','Wudil MFB','Hala MFB','Afemai MFB','Aku MFB','Iperu MFB','Bokkos MFB','Mgbidi MFB','Sim MFB','Iyamoye MFB','Ijare MFB','Otuo MFB','Ilesa MFB','Oraukwu MFB','Ile-Oluji MFB','Ilora MFB','Oke-Aro MFB','Ifedapo MFB','Rama MFB','Mautech MFB','Olabisi Onabanjo University MFB','Babcock University MFB','Pan African MFB','Corestep MFB','Iyin Ekiti MFB','FSTC MFB','Kadpoly MFB','Lagos Building Investment Company (LBIC) MFB','Adeyemi College of Education MFB','Fedpoly Bauchi MFB','Fedpoly Idah MFB','Fedpoly Ilaro MFB','Fedpoly Mubi MFB','Fedpoly Nekede MFB','Fedpoly Offa MFB','Fedpoly Oko MFB','Fedpoly Unwana MFB','Gateway MFB','Gboko MFB','Goodluck MFB','Imo State University MFB','Kogi State University MFB','Nasarawa State University MFB','Ondo State University MFB','Plateau State University MFB','Tai Solarin University MFB','University of Abuja MFB','University of Benin MFB','University of Lagos MFB','University of Maiduguri MFB','University of Nigeria MFB','University of Port Harcourt MFB','University of Uyo MFB','Usmanu Danfodiyo University MFB','Yobe State University MFB','ABU MFB','ATBU MFB','BUK MFB','COOU MFB','CRUTECH MFB','DELSU MFB','ESUT MFB','FUAM MFB','FUDMA MFB','FUGASHUA MFB','FUTO MFB','Gombe State University MFB','IBBU MFB','Ibrahim Badamasi Babangida University MFB','KASU MFB','KSU MFB','Kwara State University MFB','LAUTECH MFB','MAUTECH MFB','Olabisi Onabanjo University MFB','OOU MFB','OSUSTECH MFB','Rivers State University MFB','TASUED MFB','UMYU MFB','UNAAB MFB','UNIMAID MFB','UNIPORT MFB','UNIZIK MFB','UNN MFB','Boctrust Microfinance Bank','Wetland Microfinance Bank','Medef Microfinance Bank','Raven Microfinance Bank','CASHCONNECT MICROFINANCE BANK','NNEW WOMEN MICROFINANCE BANK','OAKLAND MICROFINANCE BANK','CEMCS Microfinance Bank','Manny Microfinance Bank','Uhuru Microfinance Bank','Molusi Microfinance Bank','Finca Microfinance Bank Limited','Waya Microfinance Bank','Sparkle MFB','Consistent Trust Microfinance Bank','CCT MFB','Firmus MFB','Peace Microfinance Bank','Oloja MFB','Bankly MFB','Payday','Aramoko MFB','Akwa Savings & Loans Limited','Alert MFB','Fedeth MFB','Bosak MFB','Gbede MFB','IKENNE MFB','Okigwe MFB','FOCUS MFB','ISS MFB','ILISAN MFB','E-BARCS MFB','Goodnews Microfinance Bank','Fina Trust Microfinance Bank','Petra Microfinance Bank','Support MFB','AMBASSADORS MFB','Moyofade MFB','OYAN MFB','RIGO MFB','CROSSRIVER MICROFINANCE BANK','FEDERAL POLYTECHNIC NEKEDE MFB','MAINLAND MFB','GBOKO MFB','YCT MFB','UNIPORT MFB','NOWNOW','FORTIS MFB','KREDI MONEY MFB','GIGINYA MFB','GMB MFB','SMARTCASH PAYMENT SERVICE BANK','HOPEPSB','CITIZEN TRUST MFB','TANGERINE MONEY','M36','HEADQUARTERS MFB'],
        'Mortgage Banks' => ['FBN Mortgages Limited','Abbey Mortgage Bank','Platinum Mortgage Bank','Lagos Building Investment Company','Safetrust Mortgage Bank','Jubilee-Life Mortgage Bank','Infinity Trust Mortgage Bank','First Generation Mortgage Bank','Brent Mortgage Bank','Living Trust Mortgage Bank','Omoluabi Mortgage Bank','MayFresh Mortgage Bank','Resort Savings & Loans','Gateway Mortgage Bank','Century Mortgage Bank','Haggai Mortgage Bank','Imperial Homes Mortgage Bank'],
    ];
}
